name: Auto Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
      - run: |
          npm install
          npm run build
          git config user.name Noah Reinalter
          git config user.email 38698485+noahreinalter@users.noreply.github.com
          git add .
          git commit -m "Updated build file"
          git push
      - name: Latest tag
        uses: EndBug/latest-tag@v1.4.0